### ISSUE TITLE
source-files packages have moved at AVM servers.

### ISSUE THREAD

**Issue by bernhardu** [Freetz/freetz.github.io#5]
Destination of source links seems to have changed.
[kernel.html in the wiki](https://github.com/Freetz/freetz.github.io/blob/master/wiki/kernel.html#L137) points e.g. to here:
```ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7390/x_misc/opensrc/FRITZ.Box_Fon_WLAN_7390_source-files-06.80.tar.gz```
But I found that file nowadays here:
```https://osp.avm.de/fritzbox/fritzbox-7390/FRITZ.Box_Fon_WLAN_7390_source-files-06.80.tar.gz```

**Comment by olistudent** [comment]
As stated in README this is an extract of the old trac wiki. The pages are not maintained anymore and are here only for reference.
